const types = {
    SET_USER: "SET_USER",
    SIGNOUT: "SIGNOUT",
    SET_AVATAR: "SET_AVATAR",

    /**Chats */
    LOAD_CHATS: "LOAD_CHATS",
    ADD_CHAT: "ADD_CHAT",
    CREATE_CHAT: "CREATE_CHAT",
    DELETE_CHAT: "DELETE_CHAT",
    SEARCH: "SEARCH",
    CLEAR_SEARCH: "CLEAR_SEARCH",


    ADD_MESSAGE: "ADD_MESSAGE",
    ADD_CURRENT_MESSAGE: "ADD_CURRENT_MESSAGE",


    /**Current */
    SET_CURRENT: "SET_CURRENT",
    CLOSE_CURRENT: "CLOSE_CURRENT"
};

export default types;