const types = {
  SET_USER: "SET_USER",
  SIGNOUT: "SIGNOUT",
  SET_AVATAR: "SET_AVATAR",
  LOAD_CHATS: "LOAD_CHATS",
  ADD_CHAT: "ADD_CHAT",
  CREATE_CHAT: "CREATE_CHAT",
  SET_RESULTS: "SET_RESULTS",
  CLEAR_RESULTS: "CLEAR_RESULTS",
  SET_SEARCHING: "SET_SEARCHING",
  ADD_MESSAGE: "ADD_MESSAGE",
  READ_MESSAGE: "READ_MESSAGE",
  SET_CURRENT: "SET_CURRENT",
  CLOSE_CURRENT: "CLOSE_CURRENT"  
};

export default types;