const types = {
  SET_USER: "SET_USER",
  SIGNOUT: "SIGNOUT",
  SET_AVATAR: "SET_AVATAR",
  LOAD_CHATS: "LOAD_CHATS",
  ADD_CHAT: "ADD_CHAT",
  CREATE_CHAT: "CREATE_CHAT",
  DELETE_CHAT: "DELETE_CHAT",
  SEARCH: "SEARCH",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  ADD_MESSAGE: "ADD_MESSAGE",
  READ_MESSAGE: "READ_MESSAGE",
  SET_CURRENT: "SET_CURRENT",
  CLOSE_CURRENT: "CLOSE_CURRENT",
  LAZY_MESSAGES: "LAZY_MESSAGES"
};

export default types;